### ISSUE TITLE
代码运行不了

### ISSUE THREAD

**Issue by Javeni** [novicezk/midjourney-proxy#1]
报了一个
java.lang.IllegalStateException: com.neovisionaries.ws.client.HostnameUnverifiedException: The certificate of the peer does not match the expected hostname (gateway.discord.gg)
 at net.dv8tion.jda.internal.requests.WebSocketClient.connect(WebSocketClient.java:394) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]

**Comment by novicezk** [comment]
@Javeni 检查下电脑是否能科学上网

**Comment by Javeni** [comment]
net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.utils.SessionControllerAdapter.getShardedGateway(SessionControllerAdapter.java:101) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.internal.JDAImpl.getShardedGateway(JDAImpl.java:355) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.sharding.DefaultShardManager.buildInstance(DefaultShardManager.java:556) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.sharding.DefaultShardManager.login(DefaultShardManager.java:272) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2248) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2204) ~[JDA-5.0.0-beta.8.jar:5.0.0-beta.8]
	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:24) ~[classes/:na]
	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:12) ~[classes/:na]

启动就报错 @novicezk 不是代理问题，证明是可以科学上网的

**Comment by novicezk** [comment]
@Javeni 用电脑 postman 测试下能不能 post调用 https://discord.com/api/v9/interactions 接口

**Comment by novicezk** [comment]
@Javeni 科学上网试试开启全局代理；用开发工具idea之类启动的话，可能需要配置http代理
