### ISSUE TITLE
每次都出现超时，请问是什么原因呢？

### ISSUE THREAD

**Issue by jiburan999888** [novicezk/midjourney-proxy#108]
2023-05-30T19:31:54.762 [ERROR] - submit mj error AxiosError: timeout of 60000ms exceeded
    at RedirectableRequest.handleRequestTimeout (file:///app/node_modules/axios/lib/adapters/http.js:614:16)
    at RedirectableRequest.emit (node:events:513:28)
    at RedirectableRequest.emit (node:domain:489:12)
    at Timeout. (/app/node_modules/follow-redirects/index.js:169:12)
    at listOnTimeout (node:internal/timers:569:17)
    at processTimers (node:internal/timers:512:7) {
  code: 'ECONNABORTED',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 60000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.3.6',
      'Content-Length': '109',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://172.17.0.1:8080/mj',
    method: 'post',
    url: '/submit/imagine',

**Comment by novicezk** [comment]
检查proxy项目是否正常启动

**Comment by jiburan999888** [comment]
> 检查proxy项目是否正常启动

确定是正常启动的
