### ISSUE TITLE
使用docker运行容器，提示以下错误，是我哪个token没配置对吗

### ISSUE THREAD

**Issue by zxyyyzzz** [novicezk/midjourney-proxy#126]
java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:16) ~[classes!/:2.1.5]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.1.5]
Caused by: net.dv8tion.jda.api.exceptions.InvalidTokenException: The provided token is invalid!
	at com.github.novicezk.midjourney.wss.bot.CustomSessionController$1.handleResponse(CustomSessionController.java:38) ~[classes!/:2.1.5]
	at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:283) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.handleResponse(Requester.java:414) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.access$300(Requester.java:350) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:233) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:145) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:128) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:378) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:450) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:494) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:72) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:35) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at com.github.novicezk.midjourney.wss.bot.CustomSessionController.getShardedGateway(CustomSessionController.java:43) ~[classes!/:2.1.5]
	at net.dv8tion.jda.internal.JDAImpl.getShardedGateway(JDAImpl.java:355) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.sharding.DefaultShardManager.buildInstance(DefaultShardManager.java:556) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.sharding.DefaultShardManager.login(DefaultShardManager.java:272) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2248) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2204) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
	at com.github.novicezk.midjourney.wss.bot.BotWebSocketStarter.start(BotWebSocketStarter.java:35) ~[classes!/:2.1.5]
	at spring.config.BeanConfig.lambda$enableMetaChangeReceiverInitializer$1(BeanConfig.java:76) ~[classes!/:2.1.5]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14]
	at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:16) ~[classes!/:2.1.5]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.1.5]
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.1.5]

**Comment by zxyyyzzz** [comment]
我的配置文件如下
docker run -d --name mj-proxy 
 -p 8080:8080 \
 -e mj.discord.guild-id=xxx \
 -e mj.discord.channel-id=xxx \
 -e mj.discord.user-token=xxx \
 --restart=always \
 novicezk/midjourney-proxy:2.1.5

**Comment by zxyyyzzz** [comment]
配置没配置好

**Comment by Cuauhtemoc9** [comment]
> java.lang.IllegalStateException: Failed to execute ApplicationRunner at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14] at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:16) ~[classes!/:2.1.5] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.1.5] at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.1.5] at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.1.5] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.1.5] Caused by: net.dv8tion.jda.api.exceptions.InvalidTokenException: The provided token is invalid! at com.github.novicezk.midjourney.wss.bot.CustomSessionController$1.handleResponse(CustomSessionController.java:38) ~[classes!/:2.1.5] at net.dv8tion.jda.api.requests.Request.handleResponse(Request.java:283) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester$WorkTask.handleResponse(Requester.java:414) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester$WorkTask.access$300(Requester.java:350) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:233) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:145) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:128) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:378) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:450) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:494) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na] at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na] at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na] at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na] at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na] Caused by: net.dv8tion.jda.api.exceptions.ContextException: null at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.requests.Request.(Request.java:72) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.requests.RestFuture.(RestFuture.java:35) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at com.github.novicezk.midjourney.wss.bot.CustomSessionController.getShardedGateway(CustomSessionController.java:43) ~[classes!/:2.1.5] at net.dv8tion.jda.internal.JDAImpl.getShardedGateway(JDAImpl.java:355) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.sharding.DefaultShardManager.buildInstance(DefaultShardManager.java:556) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.sharding.DefaultShardManager.login(DefaultShardManager.java:272) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2248) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2204) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9] at com.github.novicezk.midjourney.wss.bot.BotWebSocketStarter.start(BotWebSocketStarter.java:35) ~[classes!/:2.1.5] at spring.config.BeanConfig.lambda$enableMetaChangeReceiverInitializer$1(BeanConfig.java:76) ~[classes!/:2.1.5] at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14] at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14] at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:16) ~[classes!/:2.1.5] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na] at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na] at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na] at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na] at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:2.1.5] at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:2.1.5] at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:2.1.5] at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:2.1.5]

环境变量没加双引号，我也这个问题好了
