### ISSUE TITLE
上传图片到discord失败

### ISSUE THREAD

**Issue by guoxietao** [novicezk/midjourney-proxy#138]
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2023-06-12 10:53:20.292 ERROR 7932 --- [           main] o.s.boot.SpringApplication               : Application run failed

java.lang.IllegalStateException: Failed to execute ApplicationRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:776) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:763) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:314) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar:2.6.14]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar:2.6.14]
	at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:16) ~[classes/:na]
Caused by: com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'gateway.discord.gg:443': Connect timed out
	at com.neovisionaries.ws.client.SocketConnector.connectSocket(SocketConnector.java:126) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:238) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:189) ~[nv-websocket-client-2.14.jar:na]
	at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2351) ~[nv-websocket-client-2.14.jar:na]
	at com.github.novicezk.midjourney.wss.user.UserWebSocketStarter.start(UserWebSocketStarter.java:74) ~[classes/:na]
	at spring.config.BeanConfig.lambda$enableMetaChangeReceiverInitializer$1(BeanConfig.java:80) ~[classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) ~[spring-boot-2.6.14.jar:2.6.14]
	... 5 common frames omitted
Caused by: java.net.SocketTimeoutException: Connect timed out
	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[na:na]
	at com.neovisionaries.ws.client.SocketInitiator$SocketRacer.run(SocketInitiator.java:126) ~[nv-websocket-client-2.14.jar:na]

2023-06-12 10:53:35.378 ERROR 7932 --- [    TaskQueue-1] c.g.n.m.service.DiscordServiceImpl       : 上传图片到discord失败

org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://discord.com/api/v9/channels/1117061977404096512/attachments": Connection timed out: connect; nested exception is java.net.ConnectException: Connection timed out: connect
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474) ~[spring-web-5.3.24.jar:5.3.24]
	at com.github.novicezk.midjourney.service.DiscordServiceImpl.postJson(DiscordServiceImpl.java:215) ~[classes/:na]
	at com.github.novicezk.midjourney.service.DiscordServiceImpl.upload(DiscordServiceImpl.java:157) ~[classes/:na]
	at com.github.novicezk.midjourney.service.TaskServiceImpl.lambda$submitImagine$0(TaskServiceImpl.java:33) ~[classes/:na]
	at com.github.novicezk.midjourney.support.TaskQueueHelper.executeTask(TaskQueueHelper.java:101) ~[classes/:na]
	at com.github.novicezk.midjourney.support.TaskQueueHelper.lambda$submitTask$1(TaskQueueHelper.java:80) ~[classes/:na]
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: java.net.ConnectException: Connection timed out: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[na:na]
	at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[na:na]
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[na:na]
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
	at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:304) ~[na:na]
	at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[na:na]
	at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:532) ~[na:na]
	at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:637) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:193) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[na:na]
	at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
	at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:179) ~[na:na]
	at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142) ~[na:na]
	at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.24.jar:5.3.24]
	at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782) ~[spring-web-5.3.24.jar:5.3.24]
	... 12 common frames omitted

**Comment by guoxietao** [comment]
https://discord.com/channels/1091685948972089495/1117061977404096512

![image](https://github.com/novicezk/midjourney-proxy/assets/16207475/e502874b-65f2-4a18-9f06-390a66708cd8)

**Comment by guoxietao** [comment]
开了全局代理还是要设置代理

**Comment by Up-K** [comment]
怎么解决的可以发下方案吗

**Comment by guoxietao** [comment]
一定要配置代理，开全局代理没用
