### ISSUE TITLE
❌ MJ服务异常, 请稍后再试

### ISSUE THREAD

**Issue by tcflying** [novicezk/midjourney-proxy#142]
2023-06-12T09:49:13.418 [INFO] - User Kin login success

2023-06-12T09:49:24.106 [INFO] - [小海哥哥,差不多先生, datoo,Kin] Kin: 欢迎使用MJ机器人<br>------------------------------<br>🎨 AI绘图命令<br>输入: /imagine prompt<br>prompt 即你提的绘画需求<br>------------------------------<br>📕 prompt附加参数 <br>1.解释: 在prompt后携带 的参数, 可以使你的绘画更别具一格<br>2.示例: /imagine prompt --ar 16:9<br>3.使用: 需要使用--key value, key和value空格隔开, 多个附加参数空格隔开<br>------------------------------<br>📗 附加参数列表<br>1. --v 版本 1,2,3,4,5 默认5, 不可与niji同用<br>2. --niji 卡通版本 空或5 默认空, 不可与v同用<br>3. --ar 横纵比 n:n 默认1:1<br>4. --q 清晰度 .25 .5 1 2 分别代表: 一般,清晰,高清,超高清,默认1<br>5. --style 风格 (4a,4b,4c)v4可用 (expressive,cute)niji5可用<br>6. --s 风格化 1-1000 (625-60000)v3

2023-06-12T09:49:37.833 [INFO] - [小海哥哥,差不多先生, datoo,Kin]  datoo: /imagine bird

2023-06-12T09:49:38.008 [ERROR] - submit mj error AxiosError: Request failed with status code 502
    at settle (file:///app/node_modules/axios/lib/core/settle.js:19:12)
    at IncomingMessage.handleStreamEnd (file:///app/node_modules/axios/lib/adapters/http.js:556:11)
    at IncomingMessage.emit (node:events:525:35)
    at IncomingMessage.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1359:12)
    at processTicksAndRejections (node:internal/process/task_queues:82:21) {
  code: 'ERR_BAD_RESPONSE',
  config: {
    transitional: {
      silentJSONParsing: true,
      forcedJSONParsing: true,
      clarifyTimeoutError: false
    },
    adapter: [ 'xhr', 'http' ],
    transformRequest: [ [Function: transformRequest] ],
    transformResponse: [ [Function: transformResponse] ],
    timeout: 60000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    maxContentLength: -1,
    maxBodyLength: -1,
    env: { FormData: [Function], Blob: [class Blob] },
    validateStatus: [Function: validateStatus],
    headers: AxiosHeaders {
      Accept: 'application/json, text/plain, */*',
      'Content-Type': 'application/json',
      'User-Agent': 'axios/1.3.6',
      'Content-Length': '124',
      'Accept-Encoding': 'gzip, compress, deflate, br'
    },
    baseURL: 'http://host.docker.internal:8080/mj',
    method: 'post',
    url: '/submit/imagine',
    data: '{"state":"小海哥哥,差不多先生, datoo,Kin: datoo","prompt":"bird","notifyHook":"http://host.docker.internal/notify"}'
  },
  request: <ref *1> ClientRequest {
    _events: [Object: null prototype] {
      abort: [Function (anonymous)],
      aborted: [Function (anonymous)],
      connect: [Function (anonymous)],
      error: [Function (anonymous)],
      socket: [Function (anonymous)],
      timeout: [Function (anonymous)],
      finish: [Function: requestOnFinish]
    },
    _eventsCount: 7,
    _maxListeners: undefined,
    outputData: [],
    outputSize: 0,
    writable: true,
    destroyed: false,
    _last: true,
    chunkedEncoding: false,
    shouldKeepAlive: false,
    maxRequestsOnConnectionReached: false,
    _defaultKeepAlive: true,
    useChunkedEncodingByDefault: true,
    sendDate: false,
    _removedConnection: false,
    _removedContLen: false,
    _removedTE: false,
    strictContentLength: false,
    _contentLength: '124',
    _hasBody: true,
    _trailer: '',
    finished: true,
    _headerSent: true,
    _closed: false,
    socket: Socket {
      connecting: false,
      _hadError: false,
      _parent: null,
      _host: null,
      _closeAfterHandlingError: false,
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      _writableState: [WritableState],
      allowHalfOpen: false,
      _sockname: null,
      _pendingData: null,
      _pendingEncoding: '',
      server: null,
      _server: null,
      parser: null,
      _httpMessage: [Circular *1],
      timeout: 60000,
      [Symbol(async_id_symbol)]: 4550,
      [Symbol(kHandle)]: [TCP],
      [Symbol(lastWriteQueueSize)]: 0,
      [Symbol(timeout)]: Timeout {
        _idleTimeout: 60000,
        _idlePrev: [TimersList],
        _idleNext: [Timeout],
        _idleStart: 121668,
        _onTimeout: [Function: bound ],
        _timerArgs: undefined,
        _repeat: null,
        _destroyed: false,
        [Symbol(refed)]: false,
        [Symbol(kHasPrimitive)]: false,
        [Symbol(asyncId)]: 4559,
        [Symbol(triggerId)]: 4552
      },
      [Symbol(kBuffer)]: null,
      [Symbol(kBufferCb)]: null,
      [Symbol(kBufferGen)]: null,
      [Symbol(kCapture)]: false,
      [Symbol(kSetNoDelay)]: true,
      [Symbol(kSetKeepAlive)]: true,
      [Symbol(kSetKeepAliveInitialDelay)]: 60,
      [Symbol(kBytesRead)]: 0,
      [Symbol(kBytesWritten)]: 0
    },
    _header: 'POST http://host.docker.internal:8080/mj/submit/imagine HTTP/1.1\r\n' +
      'Accept: application/json, text/plain, */*\r\n' +
      'Content-Type: application/json\r\n' +
      'User-Agent: axios/1.3.6\r\n' +
      'Content-Length: 124\r\n' +
      'Accept-Encoding: gzip, compress, deflate, br\r\n' +
      'host: host.docker.internal:8080\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: nop],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 80,
      protocol: 'http:',
      options: [Object: null prototype],
      requests: [Object: null prototype] {},
      sockets: [Object: null prototype],
      freeSockets: [Object: null prototype] {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'lifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'POST',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    joinDuplicateHeaders: undefined,
    path: 'http://host.docker.internal:8080/mj/submit/imagine',
    _ended: true,
    res: IncomingMessage {
      _readableState: [ReadableState],
      _events: [Object: null prototype],
      _eventsCount: 4,
      _maxListeners: undefined,
      socket: [Socket],
      httpVersionMajor: 1,
      httpVersionMinor: 1,
      httpVersion: '1.1',
      complete: true,
      rawHeaders: [Array],
      rawTrailers: [],
      joinDuplicateHeaders: undefined,
      aborted: false,
      upgrade: false,
      url: '',
      method: null,
      statusCode: 502,
      statusMessage: 'Bad Gateway',
      client: [Socket],
      _consuming: false,
      _dumped: false,
      req: [Circular *1],
      responseUrl: 'http://host.docker.internal:8080/mj/submit/imagine',
      redirects: [],
      [Symbol(kCapture)]: false,
      [Symbol(kHeaders)]: [Object],
      [Symbol(kHeadersCount)]: 4,
      [Symbol(kTrailers)]: null,
      [Symbol(kTrailersCount)]: 0
    },
    aborted: false,
    timeoutCb: null,
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: '192.168.50.236',
    protocol: 'http:',
    _redirectable: Writable {
      _writableState: [WritableState],
      _events: [Object: null prototype],
      _eventsCount: 3,
      _maxListeners: undefined,
      _options: [Object],
      _ended: true,
      _ending: true,
      _redirectCount: 0,
      _redirects: [],
      _requestBodyLength: 124,
      _requestBodyBuffers: [],
      _onNativeResponse: [Function (anonymous)],
      _currentRequest: [Circular *1],
      _currentUrl: 'http://host.docker.internal:8080/mj/submit/imagine',
      _timeout: null,
      [Symbol(kCapture)]: false
    },
    [Symbol(kCapture)]: false,
    [Symbol(kBytesWritten)]: 0,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      accept: [Array],
      'content-type': [Array],
      'user-agent': [Array],
      'content-length': [Array],
      'accept-encoding': [Array],
      host: [Array]
    },
    [Symbol(errored)]: null,
    [Symbol(kUniqueHeaders)]: null
  },
  response: {
    status: 502,
    statusText: 'Bad Gateway',
    headers: AxiosHeaders { connection: 'close', 'content-length': '0' },
    config: {
      transitional: [Object],
      adapter: [Array],
      transformRequest: [Array],
      transformResponse: [Array],
      timeout: 60000,
      xsrfCookieName: 'XSRF-TOKEN',
      xsrfHeaderName: 'X-XSRF-TOKEN',
      maxContentLength: -1,
      maxBodyLength: -1,
      env: [Object],
      validateStatus: [Function: validateStatus],
      headers: [AxiosHeaders],
      baseURL: 'http://host.docker.internal:8080/mj',
      method: 'post',
      url: '/submit/imagine',
      data: '{"state":"小海哥哥,差不多先生, datoo,Kin: datoo","prompt":"bird","notifyHook":"http://host.docker.internal/notify"}'
    },
    request: <ref *1> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 7,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      maxRequestsOnConnectionReached: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: true,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      strictContentLength: false,
      _contentLength: '124',
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      _closed: false,
      socket: [Socket],
      _header: 'POST http://host.docker.internal:8080/mj/submit/imagine HTTP/1.1\r\n' +
        'Accept: application/json, text/plain, */*\r\n' +
        'Content-Type: application/json\r\n' +
        'User-Agent: axios/1.3.6\r\n' +
        'Content-Length: 124\r\n' +
        'Accept-Encoding: gzip, compress, deflate, br\r\n' +
        'host: host.docker.internal:8080\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: nop],
      agent: [Agent],
      socketPath: undefined,
      method: 'POST',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      joinDuplicateHeaders: undefined,
      path: 'http://host.docker.internal:8080/mj/submit/imagine',
      _ended: true,
      res: [IncomingMessage],
      aborted: false,
      timeoutCb: null,
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: '192.168.50.236',
      protocol: 'http:',
      _redirectable: [Writable],
      [Symbol(kCapture)]: false,
      [Symbol(kBytesWritten)]: 0,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype],
      [Symbol(errored)]: null,
      [Symbol(kUniqueHeaders)]: null
    },
    data: ''
  }
}

2023-06-12T09:49:38.028 [INFO] - [小海哥哥,差不多先生, datoo,Kin] Kin: @ datoo
❌ MJ服务异常, 请稍后再试

2023-06-12T09:49:38.281 [INFO] - [小海哥哥,差不多先生, datoo,Kin] Kin: @ datoo <br>❌ MJ服 务异常, 请稍后再试

**Comment by tcflying** [comment]
2023-06-12 23:16:29 2023-06-12 23:16:29.331 ERROR 1 --- [    TaskQueue-2] c.g.n.m.support.TaskQueueHelper          : task execute error
2023-06-12 23:16:29 
2023-06-12 23:16:29 org.springframework.web.client.ResourceAccessException: I/O error on POST request for "https://discord.com/api/v9/interactions": discord.com; nested exception is java.net.UnknownHostException: discord.com
2023-06-12 23:16:29 at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:791) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at org.springframework.web.client.RestTemplate.execute(RestTemplate.java:717) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at org.springframework.web.client.RestTemplate.postForEntity(RestTemplate.java:474) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.service.DiscordServiceImpl.postJson(DiscordServiceImpl.java:215) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.service.DiscordServiceImpl.postJson(DiscordServiceImpl.java:206) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.service.DiscordServiceImpl.postJsonAndCheckStatus(DiscordServiceImpl.java:220) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.service.DiscordServiceImpl.imagine(DiscordServiceImpl.java:81) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.service.TaskServiceImpl.lambda$submitImagine$0(TaskServiceImpl.java:49) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.support.TaskQueueHelper.executeTask(TaskQueueHelper.java:101) ~[classes!/:2.2]
2023-06-12 23:16:29 at com.github.novicezk.midjourney.support.TaskQueueHelper.lambda$submitTask$1(TaskQueueHelper.java:80) ~[classes!/:2.2]
2023-06-12 23:16:29 at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
2023-06-12 23:16:29 at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
2023-06-12 23:16:29 at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
2023-06-12 23:16:29 at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
2023-06-12 23:16:29 at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
2023-06-12 23:16:29 Caused by: java.net.UnknownHostException: discord.com
2023-06-12 23:16:29 at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:567) ~[na:na]
2023-06-12 23:16:29 at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
2023-06-12 23:16:29 at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:174) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.NetworkClient.doConnect(NetworkClient.java:183) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:498) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.http.HttpClient.openServer(HttpClient.java:603) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:266) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:380) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:189) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1242) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1128) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:175) ~[na:na]
2023-06-12 23:16:29 at java.base/sun.net.www.protocol.https.HttpsURLConnectionImpl.connect(HttpsURLConnectionImpl.java:142) ~[na:na]
2023-06-12 23:16:29 at org.springframework.http.client.SimpleBufferingClientHttpRequest.executeInternal(SimpleBufferingClientHttpRequest.java:76) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at org.springframework.http.client.AbstractBufferingClientHttpRequest.executeInternal(AbstractBufferingClientHttpRequest.java:48) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at org.springframework.http.client.AbstractClientHttpRequest.execute(AbstractClientHttpRequest.java:66) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 at org.springframework.web.client.RestTemplate.doExecute(RestTemplate.java:782) ~[spring-web-5.3.24.jar!/:5.3.24]
2023-06-12 23:16:29 ... 14 common frames omitted
2023-06-12 23:16:29 
2023-06-12 23:16:31 2023-06-12 23:16:31.365  WARN 1 --- [    TaskQueue-2] c.g.n.m.service.NotifyServiceImpl        : 推送任务变更失败, 任务ID: 7285877093025669, 描述: 502 Bad Gateway: [no body]

**Comment by RolloTomasiii** [comment]
大佬，这个问题是怎么解决的
