### ISSUE TITLE
MJ图片生成成功，没有回调进度显示，最终回调显示任务超时

### ISSUE THREAD

**Issue by vipF** [novicezk/midjourney-proxy#175]
2023-06-19 16:04:21.915 DEBUG 1892234 --- [ TaskNotify-6] c.g.n.m.service.NotifyServiceImpl : 推送任务变更成功, 任务ID: 0191304188213322, status: SUBMITTED
2023-06-19 16:04:22.553 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : CREATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (Waiting to start)
2023-06-19 16:04:33.424 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (0%) (fast)
2023-06-19 16:04:39.429 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (15%) (fast)
2023-06-19 16:04:45.864 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (31%) (fast)
2023-06-19 16:04:52.719 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (46%) (fast)
2023-06-19 16:04:59.614 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (62%) (fast)
2023-06-19 16:05:06.704 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (78%) (fast)
2023-06-19 16:05:13.117 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : UPDATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (93%) (fast)
2023-06-19 16:05:24.432 DEBUG 1892234 --- [inWS-ReadThread] c.g.n.m.wss.bot.BotMessageListener : CREATE - Midjourney Bot: **[0191304188213322]fly horse --v 5.1** - &lt;@1110182893621350490&gt; (fast)
2023-06-19 16:09:42.062 DEBUG 1892234 --- [ scheduling-1] c.g.n.m.support.TaskTimeoutSchedule : task timeout, id: 0191304188213322
2023-06-19 16:09:42.064 ERROR 1892234 --- [ scheduling-1] o.s.s.s.TaskUtils$LoggingErrorHandler : Unexpected error occurred in scheduled task

java.util.ConcurrentModificationException: null
at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1631) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499) ~[na:na]
at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:150) ~[na:na]
at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:173) ~[na:na]
at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234) ~[na:na]
at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596) ~[na:na]
at com.github.novicezk.midjourney.support.TaskTimeoutSchedule.checkTasks(TaskTimeoutSchedule.java:27) ~[classes!/:2.2.3]
at jdk.internal.reflect.GeneratedMethodAccessor6.invoke(Unknown Source) ~[na:na]
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
at org.springframework.scheduling.support.ScheduledMethodRunnable.run(ScheduledMethodRunnable.java:84) ~[spring-context-5.3.24.jar!/:5.3.24]
at org.springframework.scheduling.support.DelegatingErrorHandlingRunnable.run(DelegatingErrorHandlingRunnable.java:54) ~[spring-context-5.3.24.jar!/:5.3.24]
at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
at java.base/java.util.concurrent.FutureTask.runAndReset(FutureTask.java:305) ~[na:na]
at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:305) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]

2023-06-19 16:09:42.086 DEBUG 1892234 --- [ TaskNotify-8] c.g.n.m.service.NotifyServiceImpl : 推送任务变更成功, 任务ID: 0191304188213322, status: FAILURE

**Comment by vipF** [comment]
已解

**Comment by yunli-GitHub** [comment]
怎么处理好的

**Comment by vipF** [comment]
> 怎么处理好的

我是因为content里带了/imagine，去掉就行了

**Comment by Neph0s** [comment]
> > 怎么处理好的
> 
> 我是因为content里带了/imagine，去掉就行了

是说把/i改成了/imagine吗？
