### ISSUE TITLE
 Failed to connect to 'gateway.discord.gg:443': Network is unreachable

### ISSUE THREAD

**Issue by trentluo** [novicezk/midjourney-proxy#194]
我的主机是可以翻墙的，大佬能指导下是什么原因吗，少了什么配置？
Caused by: com.neovisionaries.ws.client.WebSocketException: Failed to connect to 'gateway.discord.gg:443': Network is unreachable
        at com.neovisionaries.ws.client.SocketConnector.connectSocket(SocketConnector.java:126) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.SocketConnector.doConnect(SocketConnector.java:238) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.SocketConnector.connect(SocketConnector.java:189) ~[nv-websocket-client-2.14.jar!/:na]
        at com.neovisionaries.ws.client.WebSocket.connect(WebSocket.java:2351) ~[nv-websocket-client-2.14.jar!/:na]
        at com.github.novicezk.midjourney.wss.user.UserWebSocketStarter.start(UserWebSocketStarter.java:74) ~[classes!/:2.2]
        at spring.config.BeanConfig.lambda$enableMetaChangeReceiverInitializer$1(BeanConfig.java:80) ~[classes!/:2.2]
        at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:773) ~[spring-boot-2.6.14.jar!/:2.6.14]
        ... 13 common frames omitted
Caused by: java.net.SocketException: Network is unreachable
        at java.base/sun.nio.ch.Net.connect0(Native Method) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:579) ~[na:na]
        at java.base/sun.nio.ch.Net.connect(Net.java:568) ~[na:na]
        at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:588) ~[na:na]
        at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
        at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
        at java.base/sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:299) ~[na:na]
        at com.neovisionaries.ws.client.SocketInitiator$SocketRacer.run(SocketInitiator.java:126) ~[nv-websocket-client-2.14.jar!/:na]

**Comment by zw5685669** [comment]
兄弟解决了没。我也碰到这个情况。全局代理了也不行。

**Comment by BenWwwn** [comment]
别在Windows运行，去Linux运行就解决了

**Comment by pandaOreo** [comment]
> 除了在Windows运行，去Linux运行就解决了

在docker里面也没法运行
