### ISSUE TITLE
容器里已经可以科学上网访问discord，但还是访问submit接口没响应

### ISSUE THREAD

**Issue by jingb** [novicezk/midjourney-proxy#51]
如题，启动docker的时候带了代理的参数

> docker run ………………
> -e HTTP_PROXY=192.168.0.148:7890 \
>  -e HTTPS_PROXY=192.168.0.148:7890 \
>  --restart=always \
>  novicezk/midjourney-proxy:1.4

容器里访问discord的主页，是可以通的
> docker exec 89d67b21764693e curl https://discord.com
>   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
>                                  Dload  Upload   Total   Spent    Left  Speed
>   0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0<!DOCTYPE html><html lang="en-US">
> <head>
>   <meta charset="utf-8" />
>   <meta name="google-site-verification" content="nubQ83kz2YYRrleJaYf_CYbvDZ6lXVl-NL_MWX1Uj9Y" />
>   <meta name="msvalidate.01" content="330DC90484A4B7B61B36AD65E89B47AE" />
>   <meta name="viewport" content="width=device-width, initial-scale=1.0" />
>   <meta property="og:type" content="website" /><meta property="og:url" content="https://discord.com/" />
>   
>   
>   <meta property="og:site_name" content="Discord" />

访问 /mj/trigger/submit 接口一整个没有任何响应

部分日志，主要没显示访问了哪个地址超时，也看不出什么

> 2023-05-13 16:16:53.802  INFO 1 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : Initializing Servlet 'dispatcherServlet'
> 2023-05-13 16:16:53.805  INFO 1 --- [nio-8080-exec-3] o.s.web.servlet.DispatcherServlet        : Completed initialization in 3 ms
> 2023-05-13 16:16:58.848 ERROR 1 --- [eLimit-Worker 1] n.d.jda.internal.requests.Requester      : There was an I/O error while executing a REST request: Connect timed out
> 2023-05-13 16:16:58.863  INFO 1 --- [           main] ConditionEvaluationReportLoggingListener :
> 
> Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
> 2023-05-13 16:16:58.880 ERROR 1 --- [           main] o.s.boot.SpringApplication               : Application run failed
> 
> net.dv8tion.jda.api.exceptions.ErrorResponseException: -1: java.net.SocketTimeoutException
> 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:227) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.utils.SessionControllerAdapter.getShardedGateway(SessionControllerAdapter.java:101) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.JDAImpl.getShardedGateway(JDAImpl.java:355) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManager.buildInstance(DefaultShardManager.java:556) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManager.login(DefaultShardManager.java:272) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2248) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2204) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:24) ~[classes!/:1.4]
> 	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:12) ~[classes!/:1.4]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:108) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:78) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:78) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:13) ~[classes!/:1.4]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:1.4]
> Caused by: java.net.SocketTimeoutException: Connect timed out
> 	at java.base/sun.nio.ch.NioSocketImpl.timedFinishConnect(NioSocketImpl.java:546) ~[na:na]
> 	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:597) ~[na:na]
> 	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327) ~[na:na]
> 	at java.base/java.net.Socket.connect(Socket.java:633) ~[na:na]
> 	at okhttp3.internal.platform.Platform.connectSocket(Platform.java:130) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:263) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:183) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.ExchangeFinder.findConnection(ExchangeFinder.java:224) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.ExchangeFinder.findHealthyConnection(ExchangeFinder.java:108) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.ExchangeFinder.find(ExchangeFinder.java:88) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.Transmitter.newExchange(Transmitter.java:169) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:41) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:94) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:88) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:142) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:117) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:229) ~[okhttp-3.14.9.jar!/:na]
> 	at okhttp3.RealCall.execute(RealCall.java:81) ~[okhttp-3.14.9.jar!/:na]
> 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:190) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:264) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:145) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.Requester.execute(Requester.java:128) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.Requester$WorkTask.execute(Requester.java:378) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.execute(SequentialRestRateLimiter.java:450) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.SequentialRestRateLimiter$Bucket.run(SequentialRestRateLimiter.java:494) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539) ~[na:na]
> 	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264) ~[na:na]
> 	at java.base/java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:304) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
> 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
> 	at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
> Caused by: net.dv8tion.jda.api.exceptions.ContextException: null
> 	at net.dv8tion.jda.api.exceptions.ContextException.here(ContextException.java:54) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.Request.<init>(Request.java:72) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.RestFuture.<init>(RestFuture.java:35) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.RestActionImpl.submit(RestActionImpl.java:209) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.requests.RestActionImpl.complete(RestActionImpl.java:219) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.requests.RestAction.complete(RestAction.java:632) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.utils.SessionControllerAdapter.getShardedGateway(SessionControllerAdapter.java:101) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.internal.JDAImpl.getShardedGateway(JDAImpl.java:355) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManager.buildInstance(DefaultShardManager.java:556) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManager.login(DefaultShardManager.java:272) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2248) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at net.dv8tion.jda.api.sharding.DefaultShardManagerBuilder.build(DefaultShardManagerBuilder.java:2204) ~[JDA-5.0.0-beta.9.jar!/:5.0.0-beta.9]
> 	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:24) ~[classes!/:1.4]
> 	at com.github.novicezk.midjourney.support.DiscordStarter.onApplicationEvent(DiscordStarter.java:12) ~[classes!/:1.4]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.doInvokeListener(SimpleApplicationEventMulticaster.java:176) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.invokeListener(SimpleApplicationEventMulticaster.java:169) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.event.SimpleApplicationEventMulticaster.multicastEvent(SimpleApplicationEventMulticaster.java:143) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:421) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.context.support.AbstractApplicationContext.publishEvent(AbstractApplicationContext.java:378) ~[spring-context-5.3.24.jar!/:5.3.24]
> 	at org.springframework.boot.context.event.EventPublishingRunListener.started(EventPublishingRunListener.java:108) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.lambda$started$5(SpringApplicationRunListeners.java:78) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511) ~[na:na]
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:120) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.doWithListeners(SpringApplicationRunListeners.java:114) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplicationRunListeners.started(SpringApplicationRunListeners.java:78) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:313) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1317) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1306) ~[spring-boot-2.6.14.jar!/:2.6.14]
> 	at com.github.novicezk.midjourney.ProxyApplication.main(ProxyApplication.java:13) ~[classes!/:1.4]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
> 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
> 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
> 	at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
> 	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[app.jar:1.4]
> 	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88) ~[app.jar:1.4]
> 
>

**Comment by novicezk** [comment]
启动失败了，websocket连接discord超时，排查网络代理问题

**Comment by jingb** [comment]
容器里网络访问discord的主页没问题的

```
docker exec 89d67b21764693e curl https://discord.com/
% Total % Received % Xferd Average Speed Time Time Time Current
Dload Upload Total Spent Left Speed
0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
………………  后面响应了一大坨html网页
```

**Comment by heyi-byte** [comment]
> 容器里网络访问discord的主页没问题的
> 
> ```
> docker exec 89d67b21764693e curl https://discord.com/
> % Total % Received % Xferd Average Speed Time Time Time Current
> Dload Upload Total Spent Left Speed
> 0 0 0 0 0 0 0 0 --:--:-- --:--:-- --:--:-- 0
> ………………  后面响应了一大坨html网页
> ```

请问解决了吗，我也遇到了这个问题

**Comment by ucmac** [comment]
我也遇到了

**Comment by shenhuaxx** [comment]
参考 [https://github.com/novicezk/midjourney-proxy/issues/59](url) 中我的回答

**Comment by 523013183** [comment]
> 参考 [issue](https://github.com/novicezk/midjourney-proxy/issues/59) 中我的回答

我按这设置的代理， 还是报错了呢。
